Fixed unsubscribe error on macos (#124)
Co-authored-by: dol3 <75476445+dol3@users.noreply.github.com>
Co-authored-by: Piotr Sarzyński <piotr.sarzynski@minebest.com>

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -8,16 +8,17 @@ GIT_REPO=https://github.com/bitcoinvault/electrum-vault
 
 export GCC_STRIP_BINARIES="1"
 
-. $(dirname "$0")/base.sh
+
+. "$(dirname "$0")/../build_tools_util.sh"
+
 
 CONTRIB_OSX="$(dirname "$(realpath "$0")")"
 CONTRIB="$CONTRIB_OSX/.."
 ROOT_FOLDER="$CONTRIB/.."
 
 src_dir=$(dirname "$0")
-cd $src_dir/../..
+cd "$src_dir/../.."
 
-export PYTHONHASHSEED=22
 CONNECTED_NET='btcv_mainnet' # indicator for what "net" app is builded for
 VERSION=$CONNECTED_NET-`git branch --show-current | tr "/" -`-`git describe --tags --always` # --dirty could be added, but we change neetwork on the fly so it would be dirty always (if not mainnet)
 which brew > /dev/null 2>&1 || fail "Please install brew from https://brew.sh/ to continue"
@@ -39,9 +40,31 @@ else
     warn "Code signing DISABLED. Specify a valid macOS Developer identity installed on the system to enable signing."
 fi
 
+
+function DoCodeSignMaybe { # ARGS: infoName fileOrDirName
+    infoName="$1"
+    file="$2"
+    deep=""
+    if [ -z "$CODESIGN_CERT" ]; then
+        # no cert -> we won't codesign
+        return
+    fi
+    if [ -d "$file" ]; then
+        deep="--deep"
+    fi
+    if [ -z "$infoName" ] || [ -z "$file" ] || [ ! -e "$file" ]; then
+        fail "Argument error to internal function DoCodeSignMaybe()"
+    fi
+    hardened_arg="--entitlements=${CONTRIB_OSX}/entitlements.plist -o runtime"
+
+    info "Code signing ${infoName}..."
+    codesign -f -v $deep -s "$CODESIGN_CERT" $hardened_arg "$file" || fail "Could not code sign ${infoName}"
+}
+
+
 info "Installing Python $PYTHON_VERSION"
 export PATH="~/.pyenv/bin:~/.pyenv/shims:~/Library/Python/3.7/bin:$PATH"
-if [ -d "~/.pyenv" ]; then
+if [ -d "${HOME}/.pyenv" ]; then
   pyenv update
 else
   curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash > /dev/null 2>&1
@@ -52,10 +75,12 @@ fail "Unable to use Python $PYTHON_VERSION"
 
 break_legacy_easy_install
 
-info "install dependencies specific to binaries"
-# note that this also installs pinned versions of both pip and setuptools
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries.txt --user \
-    || fail "Could not install pyinstaller"
+# create a fresh virtualenv
+# This helps to avoid older versions of pip-installed dependencies interfering with the build.
+VENV_DIR="$CONTRIB_OSX/build-venv"
+rm -rf "$VENV_DIR"
+python3 -m venv $VENV_DIR
+source $VENV_DIR/bin/activate
 
 info "Installing build dependencies"
 python3 -m pip install --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements-build-mac.txt \
@@ -71,8 +96,8 @@ rm -rf ./dist
 
 git submodule update --init
 
-rm  -rf $BUILDDIR > /dev/null 2>&1
-mkdir $BUILDDIR
+rm  -rf "$BUILDDIR" > /dev/null 2>&1
+mkdir "$BUILDDIR"
 
 info "generating locale"
 (
@@ -81,18 +106,20 @@ info "generating locale"
         brew link --force gettext
     fi
     cd "$CONTRIB"/deterministic-build/electrum-locale
+    # we want the binary to have only compiled (.mo) locale files; not source (.po) files
+    rm -rf "$ROOT_FOLDER/electrum/locale/"
     for i in ./locale/*; do
-        dir="$ROOT_FOLDER"/electrum/$i/LC_MESSAGES
-        mkdir -p $dir
-        msgfmt --output-file=$dir/electrum.mo $i/electrum.po || true
+        dir="$ROOT_FOLDER/electrum/$i/LC_MESSAGES"
+        mkdir -p "$dir"
+        msgfmt --output-file="$dir/electrum.mo" "$i/electrum.po" || true
     done
 ) || fail "failed generating locale"
 
 
 info "Downloading libusb..."
 curl https://homebrew.bintray.com/bottles/libusb-1.0.23.high_sierra.bottle.tar.gz | \
-tar xz --directory $BUILDDIR
-cp $BUILDDIR/libusb/1.0.23/lib/libusb-1.0.dylib contrib/osx
+tar xz --directory "$BUILDDIR"
+cp "$BUILDDIR/libusb/1.0.23/lib/libusb-1.0.dylib" contrib/osx
 echo "caea266f3fc3982adc55d6cb8d9bad10f6e61f0c24ce5901aa1804618e08e14d  contrib/osx/libusb-1.0.dylib" | \
     shasum -a 256 -c || fail "libusb checksum mismatched"
 
@@ -103,12 +130,13 @@ cp "$ROOT_FOLDER"/electrum/libsecp256k1.0.dylib contrib/osx
 
 info "Building CalinsQRReader..."
 d=contrib/osx/CalinsQRReader
-pushd $d
+pushd "$d"
 rm -fr build
 # prefer building using xcode ourselves. otherwise fallback to prebuilt binary
 xcodebuild || cp -r prebuilt_qr build || fail "Could not build CalinsQRReader"
 popd
 DoCodeSignMaybe "CalinsQRReader.app" "${d}/build/Release/CalinsQRReader.app"
+
 
 info "Installing requirements..."
 python3 -m pip install --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements.txt \
@@ -127,10 +155,12 @@ python3 -m pip install --no-dependencies --no-warn-script-location . > /dev/null
 
 info "Faking timestamps..."
 for d in ~/Library/Python/ ~/.pyenv .; do
-  pushd $d
+  pushd "$d"
   find . -exec touch -t '200101220000' {} +
   popd
 done
+
+VERSION=`git describe --tags --dirty --always`
 
 info "Building binary"
 APP_SIGN="$CODESIGN_CERT" pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
@@ -152,7 +182,6 @@ if [ ! -z "$CODESIGN_CERT" ]; then
     fi
 fi
 
-
 info "Creating .DMG"
 hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
 
@@ -160,5 +189,5 @@ DoCodeSignMaybe ".DMG" "dist/electrum-${VERSION}.dmg"
 
 if [ -z "$CODESIGN_CERT" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
-    warn "Specify a valid code signing identity as the first argument to this script to enable code signing."
+    warn "Specify a valid code signing identity to enable code signing."
 fi
